In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('original.csv')

In [3]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [5]:
df.describe()

ID  Reason for Absence  Transportation Expense  \
count  700.000000          700.000000              700.000000   
mean    17.951429           19.411429              222.347143   
std     11.028144            8.356292               66.312960   
min      1.000000            0.000000              118.000000   
25%      9.000000           13.000000              179.000000   
50%     18.000000           23.000000              225.000000   
75%     28.000000           27.000000              260.000000   
max     36.000000           28.000000              388.000000   

       Distance to Work         Age  Daily Work Load Average  Body Mass Index  \
count        700.000000  700.000000               700.000000       700.000000   
mean          29.892857   36.417143               271.801774        26.737143   
std           14.804446    6.379083                40.021804         4.254701   
min            5.000000   27.000000               205.917000        19.000000   
25%           16.000000   31.000000               241.476000        24.000000   
50%           26.000000   37.000000               264.249000        25.000000   
75%           50.000000   40.000000               294.217000        31.000000   
max           52.000000   58.000000               378.884000        38.000000   

        Education    Children        Pets  Absenteeism Time in Hours  
count  700.000000  700.000000  700.000000                 700.000000  
mean     1.282857    1.021429    0.687143                   6.761429  
std      0.668090    1.112215    1.166095                  12.670082  
min      1.000000    0.000000    0.000000                   0.000000  
25%      1.000000    0.000000    0.000000                   2.000000  
50%      1.000000    1.000000    0.000000                   3.000000  
75%      1.000000    2.000000    1.000000                   8.000000  
max      4.000000    4.000000    8.000000                 120.000000

In [6]:
df_copy = df.copy()

In [7]:
df = df.drop('ID',axis=1)

In [8]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [9]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [10]:
reason = pd.get_dummies(df['Reason for Absence'],drop_first=True)

In [11]:
reason_1 = reason.loc[:,1:14].max(axis=1)

In [12]:
reason_2 = reason.loc[:,15:17].max(axis=1)

In [13]:
reason_3 = reason.loc[:,18:21].max(axis=1)

In [14]:
reason_4 = reason.loc[:,22:28].max(axis=1)

In [15]:
df = pd.concat([df,reason_1,reason_2,reason_3,reason_4],axis=1)

In [16]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours', 0, 1, 2, 3], dtype=object)

In [17]:
columns = ['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours', 'Reason_1','Reason_2', 'Reason_3','Reason_4']

In [18]:
df.columns = columns

In [19]:
df = df.drop('Reason for Absence',axis=1)

In [20]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

In [21]:
columns_reordered = ['Reason_1','Reason_2', 'Reason_3','Reason_4', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours']

In [22]:
df = df[columns_reordered]

In [23]:
type(df['Date'][0])

str

In [24]:
df['Date'] = pd.to_datetime(df['Date'], format ='%d/%m/%Y')

In [25]:
df['Month'] = df['Date'].apply(lambda x: x.month)

In [26]:
df['Day of Week'] = df['Date'].apply(lambda x: x.weekday())

In [27]:
df['Day of Week'].unique()

array([1, 2, 3, 4, 0, 6, 5], dtype=int64)

In [28]:
df.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month',
       'Day of Week'], dtype=object)

In [29]:
columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Day of Week','Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [30]:
df = df[columns]

In [31]:
df = df.drop('Date',axis=1)

In [32]:
df['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [33]:
df['Education'] = df['Education'].map({1:0,2:1,3:1,4:1})

In [34]:
df['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [35]:
df['Absenteeism Time in Hours'] = df['Absenteeism Time in Hours'].apply(lambda x :1 if x>3 else 0 )

In [36]:
df

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of Week  \
0           0         0         0         1      7            1   
1           0         0         0         0      7            1   
2           0         0         0         1      7            2   
3           1         0         0         0      7            3   
4           0         0         0         1      7            3   
..        ...       ...       ...       ...    ...          ...   
695         1         0         0         0      5            2   
696         1         0         0         0      5            2   
697         1         0         0         0      5            3   
698         0         0         0         1      5            3   
699         0         0         0         1      5            3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          1  
1                 31          0         1     0                          0  
2                 31          0         0     0                          0  
3                 24          0         2     0                          1  
4                 30          0         2     1                          0  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          1  
696               24          0         1     2                          0  
697               25          1         0     0                          1  
698               25          1         0     0                          0  
699               25          0         1     1                          0  

[700 rows x 15 columns]

In [37]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of Week  \
0         0         0         0         1      7            1   
1         0         0         0         0      7            1   
2         0         0         0         1      7            2   
3         1         0         0         0      7            3   
4         0         0         0         1      7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          1  
1               31          0         1     0                          0  
2               31          0         0     0                          0  
3               24          0         2     0                          1  
4               30          0         2     1                          0

In [38]:
X = df.drop('Absenteeism Time in Hours',axis=1)
y = df['Absenteeism Time in Hours']

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler = StandardScaler()

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
df.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month', 'Day of Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours'],
      dtype='object')

In [44]:
X_train = scaler.fit_transform(X_train)

In [45]:
X_test = scaler.transform(X_test)

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
lr = LogisticRegression() 

In [48]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
pred_lr = lr.predict(X_test)

In [50]:
lr.coef_

array([[ 2.12894678,  0.27559904,  1.59462146,  1.41064979,  0.09424263,
        -0.15314496,  0.79579601, -0.09907746, -0.28939164, -0.01088527,
         0.28426856, -0.14580513,  0.43220728, -0.37499688]])

In [51]:
lr.intercept_

array([-0.17127247])

In [52]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [53]:
print(classification_report(y_test,pred_lr))
print('\n')
print(confusion_matrix(y_test,pred_lr))
print('\n')
print(accuracy_score(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.79      0.78      0.79        82
           1       0.69      0.71      0.70        58

    accuracy                           0.75       140
   macro avg       0.74      0.74      0.74       140
weighted avg       0.75      0.75      0.75       140



[[64 18]
 [17 41]]


0.75


In [54]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [55]:
pred_knn = knn.predict(X_test)

In [56]:
print(classification_report(y_test,pred_knn))
print('\n')
print(confusion_matrix(y_test,pred_knn))
print('\n')
print(accuracy_score(y_test,pred_knn))

              precision    recall  f1-score   support

           0       0.78      0.76      0.77        82
           1       0.67      0.69      0.68        58

    accuracy                           0.73       140
   macro avg       0.72      0.72      0.72       140
weighted avg       0.73      0.73      0.73       140



[[62 20]
 [18 40]]


0.7285714285714285


In [57]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear', random_state = 0)
svc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [58]:
pred_svc = svc.predict(X_test)

In [59]:
print(classification_report(y_test,pred_svc))
print('\n')
print(confusion_matrix(y_test,pred_svc))
print('\n')
print(accuracy_score(y_test,pred_svc))

              precision    recall  f1-score   support

           0       0.78      0.82      0.80        82
           1       0.72      0.67      0.70        58

    accuracy                           0.76       140
   macro avg       0.75      0.74      0.75       140
weighted avg       0.76      0.76      0.76       140



[[67 15]
 [19 39]]


0.7571428571428571


In [60]:
from sklearn.svm import SVC
svc_k = SVC(kernel = 'rbf', random_state = 0)
svc_k.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [61]:
pred_ker = svc_k.predict(X_test)

In [62]:
print(classification_report(y_test,pred_ker))
print('\n')
print(confusion_matrix(y_test,pred_ker))
print('\n')
print(accuracy_score(y_test,pred_ker))

              precision    recall  f1-score   support

           0       0.82      0.78      0.80        82
           1       0.71      0.76      0.73        58

    accuracy                           0.77       140
   macro avg       0.77      0.77      0.77       140
weighted avg       0.77      0.77      0.77       140



[[64 18]
 [14 44]]


0.7714285714285715


In [63]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [64]:
pred_nb = nb.predict(X_test)

In [65]:
print(classification_report(y_test,pred_nb))
print('\n')
print(confusion_matrix(y_test,pred_nb))
print('\n')
print(accuracy_score(y_test,pred_nb))

              precision    recall  f1-score   support

           0       0.76      0.82      0.79        82
           1       0.71      0.64      0.67        58

    accuracy                           0.74       140
   macro avg       0.74      0.73      0.73       140
weighted avg       0.74      0.74      0.74       140



[[67 15]
 [21 37]]


0.7428571428571429


In [66]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [67]:
pred_dt = dt.predict(X_test)

In [68]:
print(classification_report(y_test,pred_dt))
print('\n')
print(confusion_matrix(y_test,pred_dt))
print('\n')
print(accuracy_score(y_test,pred_dt))

              precision    recall  f1-score   support

           0       0.75      0.80      0.78        82
           1       0.69      0.62      0.65        58

    accuracy                           0.73       140
   macro avg       0.72      0.71      0.72       140
weighted avg       0.73      0.73      0.73       140



[[66 16]
 [22 36]]


0.7285714285714285


In [69]:
from sklearn.ensemble import RandomForestClassifier
rt = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
rt.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [70]:
pred_rt = rt.predict(X_test)

In [71]:
print(classification_report(y_test,pred_rt))
print('\n')
print(confusion_matrix(y_test,pred_rt))
print('\n')
print(accuracy_score(y_test,pred_rt))

              precision    recall  f1-score   support

           0       0.78      0.79      0.79        82
           1       0.70      0.69      0.70        58

    accuracy                           0.75       140
   macro avg       0.74      0.74      0.74       140
weighted avg       0.75      0.75      0.75       140



[[65 17]
 [18 40]]


0.75
